# Generated by Django 5.2.4 on 2025-07-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
