# Generated by Django 5.2.4 on 2025-07-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_websitemeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='website',
        ),
    ]
